Fix undeclared constants on modern Linuxes
On 2012-12-14, `E820_*` constants were moved to `asm/e820.h`.

References:
- https://github.com/torvalds/linux/commit/af170c5061dd78512c469e6e2d211980cdb2c193

This resolves the following build failures:
```
src/novmm/loader/linux_setup.go:25:21: error: 'E820_RAM' undeclared here (not in a function)
 const int E820Ram = E820_RAM;
                     ^
src/novmm/loader/linux_setup.go:26:26: error: 'E820_RESERVED' undeclared here (not in a function)
 const int E820Reserved = E820_RESERVED;
                          ^
src/novmm/loader/linux_setup.go:27:22: error: 'E820_ACPI' undeclared here (not in a function)
 const int E820Acpi = E820_ACPI;
                      ^
```